version: 2
updates:
  - package-ecosystem: "pip"  # Specify the package ecosystem (Python)
    directory: "/"              # Location of the requirements file
    schedule:
      interval: "daily"        # Check for updates weekly
    commit-message:
      prefix: "fix"             # Commit message prefix for updates
    open-pull-requests-limit: 5  # Limit the number of open PRs
    ignore:
      - dependency-name: "flask" # Example: Ignore updates for Flask
        versions: ["<2.0"]       # Ignore all versions lower than 2.0
