name: Build Docker, Run Flask IP Blocklist Checker, and Scan with Docker Scout.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t flask-ip-blocklist-checker .

    - name: Run Docker container with Gunicorn
      run: |
        docker run -d -p 8000:8000 --name flask-ip-blocklist-app flask-ip-blocklist-checker
        sleep 5  # Allow some time for the container to start

    - name: Test Flask IP Blocklist Checker
      run: |
        curl --fail http://localhost:8000 || exit 1

    - name: Scan image with Docker Scout
      run: |
        docker scout cves flask-ip-blocklist-checker --format table

    - name: Cleanup
      run: |
        docker stop flask-ip-blocklist-app
        docker rm flask-ip-blocklist-app
