name: Build Docker, Run IP Sentinel, the Flask IP Blocklist Checker, and Scan with Docker Scout

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:latest .

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:${{ github.sha }}

      # - name: Scan Docker Image with Docker Scout
      #   uses: docker/scout-action@v1
      #   with:
      #     image: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.REPO_NAME }}:latest
      #     command: "scan"  # Specify the command to scan the image